# ========================================
# A+Life 홈페이지 - 로컬 개발 환경 설정
# ========================================

spring:
  # 데이터소스 - application.yml의 MSSQL 설정 사용
  # datasource:
  #   url: jdbc:h2:mem:testdb
  #   driver-class-name: org.h2.Driver
  #   username: sa
  #   password:

  # H2 콘솔 비활성화 (MSSQL 사용)
  h2:
    console:
      enabled: false
      # path: /h2-console

  # JPA 설정
  jpa:
    hibernate:
      ddl-auto: none # Legacy DB 사용 - 테이블 자동 생성 안함
    show-sql: true # SQL 로그 출력

  # Thymeleaf 캐시 비활성화 (개발 편의)
  thymeleaf:
    cache: false

  # DevTools 활성화
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true

  # 파일 업로드 설정
  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB # 단일 파일 최대 크기
      max-request-size: 200MB # 전체 요청 최대 크기
      file-size-threshold: 2KB

# 파일 저장 경로
file:
  upload:
    path: c:/apluslife/uploads # 로컬 개발 환경 업로드 경로

# 로깅 설정
logging:
  level:
    root: INFO
    com.apluslife: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.security: DEBUG
