# ========================================
# A+Life 홈페이지 - 공통 설정
# ========================================

server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      force: true
    session:
      timeout: 30m  # 세션 타임아웃 30분

spring:
  application:
    name: AplusLife Homepage

  profiles:
    active: local  # 기본 프로파일: local

  # Database 설정
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://172.17.252.64:1433;databaseName=LifeWeb;encrypt=false;trustServerCertificate=true
    username: AplusWeb
    password: dnpq668@#1

  # Thymeleaf 공통 설정
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8

  # JPA 공통 설정
  jpa:
    hibernate:
      ddl-auto: none  # 기간계 DB 사용 - 스키마 변경 안함
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.SQLServerDialect
        jdbc:
          charset: UTF-8

  # HTTP 메시지 컨버터 UTF-8 설정
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

# 로깅 공통 설정
logging:
  charset:
    console: UTF-8
    file: UTF-8
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
